### ISSUE TITLE
error in hw.py

### ISSUE THREAD

**Issue by Jestin1702** [ArchitWagle/auto-journal#1]
can u tell me why their is an error in im_v=shape[1] in line 46 in hw.py? i am doing it in kali. pls help

**Comment by ArchitWagle** [comment]
> can u tell me why their is an error in im_v=shape[1] in line 46 in hw.py? i am doing it in kali. pls help

Hi Jestin,
I cannot find the line `Im_v = shape[1]` in the hw.py at line no 46. Can you please verify by recloning the repo and try to run it once more. 
**If the error still persists, please post a comment with the full error text you get.**

Have a good day!

**Comment by Jestin1702** [comment]
> > can u tell me why their is an error in im_v=shape[1] in line 46 in hw.py? i am doing it in kali. pls help
> 
> Hi Jestin,
> I cannot find the line `Im_v = shape[1]` in the hw.py at line no 46. Can you please verify by recloning the repo and try to run it once more.
> **If the error still persists, please post a comment with the full error text you get.**
> 
> Have a good day!

![err](https://user-images.githubusercontent.com/63072389/89106920-dd148780-d44a-11ea-9892-29b623fe181e.png)

**Comment by Jestin1702** [comment]
> > > can u tell me why their is an error in im_v=shape[1] in line 46 in hw.py? i am doing it in kali. pls help
> > 
> > 
> > Hi Jestin,
> > I cannot find the line `Im_v = shape[1]` in the hw.py at line no 46. Can you please verify by recloning the repo and try to run it once more.
> > **If the error still persists, please post a comment with the full error text you get.**
> > Have a good day!
> 
> ![err](https://user-images.githubusercontent.com/63072389/89106920-dd148780-d44a-11ea-9892-29b623fe181e.png)

**Comment by Jestin1702** [comment]
in your repo file its line number 38.

**Comment by ArchitWagle** [comment]
added handling for when first character is numeric
